# .github/workflows/sync-upstream.yml
# Place this in your Godot fork repository
#
# Nightly job to sync with upstream godotengine/godot

name: Sync Upstream

on:
  schedule:
    # Run at 3 AM UTC every night
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for rebase
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/godotengine/godot.git
          git fetch upstream master --depth=1

      - name: Attempt rebase
        id: rebase
        continue-on-error: true
        run: |
          # Store our automation branch
          git checkout automation

          # Try to rebase onto upstream master
          if git rebase upstream/master; then
            echo "rebase_success=true" >> $GITHUB_OUTPUT
          else
            git rebase --abort
            echo "rebase_success=false" >> $GITHUB_OUTPUT
          fi

      - name: Push if rebase succeeded
        if: steps.rebase.outputs.rebase_success == 'true'
        run: |
          git push origin automation --force-with-lease

      - name: Create issue if rebase failed
        if: steps.rebase.outputs.rebase_success == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🔄 Upstream sync failed - manual rebase required';
            const body = `The nightly rebase against upstream godotengine/godot failed due to conflicts.

            **Action required:** Manual rebase needed.

            \`\`\`bash
            git fetch upstream master
            git checkout automation
            git rebase upstream/master
            # Resolve conflicts
            git push origin automation --force-with-lease
            \`\`\`

            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;

            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'upstream-sync'
            });

            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['upstream-sync', 'needs-attention']
              });
            }

  # After successful sync, trigger a build
  trigger-build:
    needs: sync
    if: success()
    uses: ./.github/workflows/build.yml
