# .github/workflows/sync-upstream-merge.yml
# Alternative: Merge-based sync (safer, never fails, but creates merge commits)

name: Sync Upstream (Merge)

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: automation
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/godotengine/godot.git
          git fetch upstream master

          # Check if we're behind upstream
          BEHIND=$(git rev-list --count HEAD..upstream/master)

          if [ "$BEHIND" -gt 0 ]; then
            echo "We are $BEHIND commits behind upstream, merging..."
            git merge upstream/master -m "Merge upstream godotengine/godot"
            git push origin automation
          else
            echo "Already up to date with upstream"
          fi

      - name: Summary
        run: |
          echo "### Sync Complete ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Branch \`automation\` is now synced with \`godotengine/godot:master\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Our commits on top:**" >> $GITHUB_STEP_SUMMARY
          git log upstream/master..HEAD --oneline | head -20 >> $GITHUB_STEP_SUMMARY
